# {
#    "iss": "Online JWT Builder",
#    "iat": 1609243412,
#    "exp": 1640779412,
#    "aud": "app.com",
#    "sub": "cane",
#    "groups": [
#        "LOGIN",
#        "APP_ADMIN"
#    ]
#}
test.jwt.token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2MDkyNDM0MTIsImV4cCI6MTY0MDc3OTQxMiwiYXVkIjoiYXBwLmNvbSIsInN1YiI6ImNhbmUiLCJncm91cHMiOlsiTE9HSU4iLCJBUFBfQURNSU4iXX0.J6Gi3vgFo631Wbfh6MakEYzZxkZuiken-hs5RFCFOts'

spring:
  security:
    user:
      name: test
      password: '{noop}pass'
      roles: USER
